#!/bin/bash
# Setup a machine for Sublime Text 2
echo "configuring sublime-text-2..."
set -x

ZSH='~/.dotfiles'
# symlink settings in
sublime_dir=$HOME/.config/sublime-text-2/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -ns "$ZSH/sublime2/User" "$sublime_dir"

# Grab the Sublime Package Control
rm -rf "$HOME/.config/sublime-text-2/Installed Packages/Package Control.sublime-package"
wget -P $HOME/.config/sublime-text-2/Installed\ Packages/ http://sublime.wbond.net/Package%20Control.sublime-package

# cp more Packages
packs=$ZSH/sublime2/Packages

for f in $(ls $packs/); do
  rm -rf "$sublime_dir/$f"
  ln -ns "$packs/$f" "$sublime_dir/$f"
done
