#!/bin/bash
# Setup a machine for Sublime Text 2

dotdir="$HOME/.dotfiles"

# Symlink settings in
sublime_dir=$HOME/.config/sublime-text-2/Packages
mv "$sublime_dir/User" "$sublime_dir/User.backup"
ln -ns "$dotdir/sublime2/User" "$sublime_dir"

# Grab the Sublime Package Control
rm -rf "$HOME/.config/sublime-text-2/Installed Packages/Package Control.sublime-package"
wget --quiet -P $HOME/.config/sublime-text-2/Installed\ Packages/ http://sublime.wbond.net/Package%20Control.sublime-package

# cp more Packages
packs=$dotdir/sublime2/Packages

for f in $packs/*; do
  fname=`basename "$f"`
  rm -rf "$sublime_dir/$fname"
  cp -r "$f" "$sublime_dir/"
done

sudo ln -fs $HOME/apps/sublime2/sublime_text /usr/bin/subl
