#!/bin/bash

## SOME LIBS, VIM AND MAKE
sudo apt-get update && sudo apt-get install build-essential zlib1g-dev libreadline-dev libssl-dev libmagickwand-dev libmysqlclient-dev vim make -y

## RBENV
. ~/.dotfiles/script/rbenv.sh

## LINKS TO SHARED FOLDER
. ~/.dotfiles/script/shared.sh

# Run the install (I'd like to pull this out of rake, eventually)
gem install rake
rake install

