#!/bin/bash

## SOME LIBS, VIM AND MAKE
sudo apt-get update && sudo apt-get install build-essential zlib1g-dev libreadline-dev libssl-dev libmagickwand-dev libmysqlclient-dev vim make libxslt1-dev rar unrar -y

## ZSH
. ~/.dotfiles/install/zsh.sh

