#!/bin/bash

eclipse=$HOME/.local/share/applications/eclipse.desktop

if [[ ! -e $eclipse ]]; then
  echo "[Desktop Entry]" >> $eclipse
  echo "Name=Eclipse" >> $eclipse
  echo "GenericName=Eclipse" >> $eclipse
  echo "Exec=$HOME/apps/eclipse/eclipse" >> $eclipse
  echo "Terminal=false" >> $eclipse
  echo "Type=Application" >> $eclipse
  echo "Icon=$HOME/apps/eclipse/icon.xpm" >> $eclipse
  echo "Categories=Accessories;" >> $eclipse
  echo "StartupNotify=true" >> $eclipse
fi
