#!/bin/bash

defaults=$HOME/.local/share/applications/defaults.list
sublime=$HOME/.local/share/applications/sublime2.desktop

entry=`grep sublime $defaults 2>/dev/null`

if [[ "$entry" == "" ]]; then
  echo [Default Applications] >> $defaults
  echo text/plain=sublime2.desktop >> $defaults
fi

if [[ ! -e $sublime ]]; then
  echo "[Desktop Entry]" >> $sublime
  echo "Name=Sublime 2" >> $sublime
  echo "GenericName=Sublime Text Editor" >> $sublime
  echo "Exec=subl" >> $sublime
  echo "Terminal=false" >> $sublime
  echo "Type=Application" >> $sublime
  echo "Icon=$HOME/apps/sublime2/Icon/256x256/sublime_text.png" >> $sublime
  echo "Categories=Accessories;" >> $sublime
  echo "StartupNotify=true" >> $sublime
fi
